### ISSUE TITLE
Danmaku blink on iPadOS

### ISSUE THREAD

**Issue by oocococo** [MoePlayer/DPlayer#946]
# The steps to reproduce.
Just open the demo on my Safari on iPad.

# Information
Dplayer: V1.26.0
OS: iPadOS 13.6
Browser: Safari

# Example

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39755142/88494483-e0da8100-cfe8-11ea-8be1-7c5748acc70e.gif)

**Comment by LouisLuBrain** [comment]
I had same issue like you, and I fixed it by fixing the source code.
the reason why danmaku blink on safari is animation(CSS property) must be completed. But in dplayer's source code, danmaku's motivation keyframes are like this:
```css
@keyframes move {
  form { transform: translateX(100%); }
}
```
chang it to :
```css
@keyframes move {
  form { transform: translateX(100%);right: 0px; }
  to { transform: translateX(100%);right: 100%; }
}
```
I don't know why? But keyframes on safari must be completed. 
(feel sorry, if I had made any grammar mistakes)

总之就是Safari上的帧动画必须是完整的，有始末位置。
